apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm-ejbca
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/matteodalgrande/k8s_argocd.git
    targetRevision: HEAD
    path: helm/ejbca  # <-- source of true into the git repo
    helm:
      valueFiles:
        - my-ejbca-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-helm-ejbca
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
