apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm-cnpg-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/matteodalgrande/k8s_argocd.git
    targetRevision: HEAD
    path: helm/cloudnative-pg-cluster  # <-- source of true into the git repo
    helm:
      valueFiles:
        - my-cloudnative-pg-cluster-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-cluster-app-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
