
fullnameOverride: argocd-helm-cnpg-cluster-db
namespaceOverride: argocd-cnpg-cluster-db

cluster:
  instances: 2

  storage:
    size: 2Gi

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  # <-- questo diventa spec.initdb nel CR
  initdb:
    database: appdb
    owner: appuser
    secret:
      name: my-db-appuser-secret

  monitoring:
    enabled: false

  primaryUpdateStrategy: unsupervised
