# values-cluster.yaml
#
# Helm values for the cnpg/cluster chart to produce:
# apiVersion: postgresql.cnpg.io/v1
# kind: Cluster
# name: my-db
# namespace: app-db

cluster:
  metadata:
    name: argo-cnpg-cluster-app-db
    namespace: cnpg-cluster-app-db

  spec:
    instances: 2

    storage:
      size: 2Gi

    imageName: ghcr.io/cloudnative-pg/postgresql:16

    bootstrap:
      initdb:
        database: appdb
        owner: appuser
        secret:
          name: my-db-appuser-secret

    monitoring:
      enablePodMonitor: false

    primaryUpdateStrategy: unsupervised
